name: run-template
on:
  issue_comment:
    types: [created]
jobs:
  comment-action:
    runs-on: [self-hosted]
    steps:
      - name: Echo Issue Comment
        run: |
          pwd && ls && /home && ip a